name: Deploy OpenAutomate Frontend

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build app
      run: npm run build
      
    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: ".next/**, public/**, package.json, package-lock.json"
        target: "/var/www/openautomate/frontend"
        
    - name: Setup server and restart frontend
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/openautomate/frontend
          npm ci --production
          pm2 restart openautomate-frontend 